/-
Copyright (c) 2026 Denise M. Case.
Released under MIT license as described in the file LICENSE.
Authors: Denise M. Case
-/
module

import all SE.IdentityRegimes.Transform.Core

public import SE.IdentityRegimes.Profile.Core
public import SE.IdentityRegimes.Transform.Core

/-!
File: SE/IdentityRegimes/Transform/NonCollapse.lean

Purpose:
Non-collapse proofs for the derived regime profiles.

CONNECTION TO THE PAPER'S DEFINITION
The paper (SE-300) defines non-collapse as: ∼_P ≠ ∼_Q, where ∼_P is the
equivalence relation on the representation space R generated by PRS-classified
transformations. Concretely, x ∼_P y iff there is a sequence of transformations
t₁…tₙ with each classificationMatrix P tᵢ = PRS that takes x to y.

The Lean definition (NonCollapsing p q := ∃ t, classificationMatrix p t ≠ classificationMatrix q t)
is sufficient for ∼_P ≠ ∼_Q via noncollapse_of_prs_difference below:
if p classifies t as PRS and q does not, then there exist representations x and
y = applyTrans t x such that x ∼_P y but x ≁_Q y, so ∼_P ≠ ∼_Q.

For the nine derived profiles, 34 of the 36 unordered profile pairs have
different PRS sets, so the argument above applies to them. (The connection to
∼_P is documented here; ∼_P and applyTrans are not defined as Lean objects.)

The other two pairs have equal PRS sets, and therefore equal PRS-generated
relations. Their matrix rows differ only at non-PRS cells:

  OBL vs NOR-C:   PRS sets are both {RF, AD}; the rows differ only at
                  BF (IGN vs BRK).
  CTX-S vs NOR-S: PRS sets are both empty; the rows differ only at
                  RC and RA (BRK vs IGN).

For these two pairs Lean proves row-level matrix distinction (NonCollapsing),
which is not the paper's ∼_P ≠ ∼_Q. The paper separates them by identity
carrier (GEN-CAR), which this file does not model. The row-level distinction
is still strict: classification_pattern_unique shows that all nine rows are
pairwise distinct.

Non-collapse is established in two stages:

  THM pairs (split pairs sharing a parent regime):
    ENR-L vs ENR-I: BF differs (PRS vs BRK). Proof: paper Prop. ENR non-collapse.
    CTX-E vs CTX-S: AD differs (PRS vs BRK). Proof: paper Prop. CTX non-collapse.
    NOR-C vs NOR-S: RF differs (PRS vs BRK). Proof: paper Prop. NOR non-collapse.

  GEN-CAR pairs (distinct parent regimes):
    The paper separates these by difference in identity carrier. Lean
    separates them by difference in classification behavior across families
    (noncollapse_of_distinct_regime); identity carriers are not modeled in
    the profile matrix.
    All 66 cross-family ordered pairs are handled by noncollapse_all_pairs.

Source: SE-300, Section 5, pairwise non-collapse matrices.
-/

namespace SE.IdentityRegimes

public section

-- RR.DEFINES: SEIR.DEF.NONCOLLAPSING
-- RR.DEFINES: SEIR.THM.NONCOLLAPSE_OF_PRS_DIFFERENCE
-- RR.DEFINES: SEIR.THM.NONCOLLAPSE_ENR_L_ENR_I
-- RR.DEFINES: SEIR.THM.NONCOLLAPSE_CTX_E_CTX_S
-- RR.DEFINES: SEIR.THM.NONCOLLAPSE_NOR_C_NOR_S
-- RR.DEFINES: SEIR.THM.NONCOLLAPSE_OF_DISTINCT_REGIME
-- RR.DEFINES: SEIR.THM.NONCOLLAPSE_ALL_PAIRS
/-- Two profiles are non-collapsing if the canonical classification matrix
    assigns different values to some transformation under those two profiles.

    This is a row-level (matrix) distinction. It gives the paper's condition
    ∼_P ≠ ∼_Q when the difference involves a PRS cell: distinct PRS sets
    induce distinct equivalence relations on the representation space.
    A difference confined to non-PRS cells does not by itself change ∼_P.
    See noncollapse_of_prs_difference for the operative connection, and the
    file header for the two profile pairs with equal PRS sets. -/
def NonCollapsing (p q : Regime) : Prop :=
  ∃ t : Transformation, classificationMatrix p t ≠ classificationMatrix q t

-- ============================================================
-- CONNECTION TO ∼_P ≠ ∼_Q
-- ============================================================

/-- Core sufficiency lemma connecting the Lean definition to the paper.

    If profile p classifies transformation t as PRS and profile q does not,
    then p and q are non-collapsing: in the representation space R, any
    pair (x, applyTrans t x) is identity-related under p but not under q,
    so ∼_P ≠ ∼_Q.

    This theorem is the operative step in each paper non-collapse proof.
    All three split-pair proofs (ENR, CTX, NOR) instantiate this pattern:
      - noncollapse_ENR_L_ENR_I: t = BF, p = ENR-L (PRS), q = ENR-I (BRK)
      - noncollapse_CTX_E_CTX_S: t = AD, p = CTX-E (PRS), q = CTX-S (BRK)
      - noncollapse_NOR_C_NOR_S: t = RF, p = NOR-C (PRS), q = NOR-S (BRK) -/
theorem noncollapse_of_prs_difference
    (p q : Regime)
    (t : Transformation)
    (hp : classificationMatrix p t = .PRS)
    (hq : classificationMatrix q t ≠ .PRS) :
    NonCollapsing p q :=
    ⟨t, by
      rw [hp]
      intro h
      exact hq h.symm
    ⟩

-- ============================================================
-- THM pairs: split-theorem witnesses from the paper
-- ============================================================

/-- ENR-L and ENR-I are non-collapsing.
    BF: PRS under ENR-L (locus persists through branching),
        BRK under ENR-I (branching produces distinct artifacts).
    Instantiates noncollapse_of_prs_difference with t = BF.
    Source: SE-300 Prop. ENR non-collapse. -/
theorem noncollapse_ENR_L_ENR_I : NonCollapsing .ENR_L .ENR_I :=
  noncollapse_of_prs_difference .ENR_L .ENR_I .BF (by decide) (by decide)

/-- CTX-E and CTX-S are non-collapsing.
    AD: PRS under CTX-E (applicability extension preserved under decomposition),
        BRK under CTX-S (decomposition alters structural organization).
    Instantiates noncollapse_of_prs_difference with t = AD.
    Source: SE-300 Prop. CTX non-collapse. -/
theorem noncollapse_CTX_E_CTX_S : NonCollapsing .CTX_E .CTX_S :=
  noncollapse_of_prs_difference .CTX_E .CTX_S .AD (by decide) (by decide)

/-- NOR-C and NOR-S are non-collapsing.
    RF: PRS under NOR-C (refinement preserves normative content),
        BRK under NOR-S (refinement alters structural organization).
    Instantiates noncollapse_of_prs_difference with t = RF.
    Source: SE-300 Prop. NOR non-collapse. -/
theorem noncollapse_NOR_C_NOR_S : NonCollapsing .NOR_C .NOR_S :=
  noncollapse_of_prs_difference .NOR_C .NOR_S .RF (by decide) (by decide)

-- ============================================================
-- GEN-CAR pairs: cross-family separation
-- ============================================================

/-- All 72 ordered pairs of distinct regimes in the derived regime set
    are non-collapsing under the canonical classification matrix. -/
theorem noncollapse_all_pairs
    (p q : Regime)
    (h : p ≠ q) :
    NonCollapsing p q := by
  cases p <;> cases q <;> simp at h <;>
    first
    | exact ⟨.BF, by decide⟩
    | exact ⟨.AD, by decide⟩
    | exact ⟨.RF, by decide⟩
    | exact ⟨.SE, by decide⟩
    | exact ⟨.AN, by decide⟩
    | exact ⟨.RC, by decide⟩

/-- Regimes with distinct parent families are non-collapsing. -/
theorem noncollapse_of_distinct_regime
    (p q : Regime)
    (h : p.family ≠ q.family) :
    NonCollapsing p q := by
  apply noncollapse_all_pairs p q
  intro hpq
  subst q
  exact h rfl

end

end SE.IdentityRegimes
