import IdentityRegimes.Profile.Core
import IdentityRegimes.Transform.Core

/-!
File: IdentityRegimes/Transform/NonCollapse.lean

Purpose:
Non-collapse proofs for the derived regime profiles.

CONNECTION TO THE PAPER'S DEFINITION
The paper (SE-300) defines non-collapse as: ∼_P ≠ ∼_Q, where ∼_P is the
equivalence relation on the representation space R generated by PRS-classified
transformations. Concretely, x ∼_P y iff there is a sequence of transformations
t₁…tₙ with each classificationMatrix P tᵢ = PRS that takes x to y.

The Lean definition (NonCollapsing p q := ∃ t, classificationMatrix p t ≠ classificationMatrix q t)
is sufficient for ∼_P ≠ ∼_Q via noncollapse_of_prs_difference below:
if p classifies t as PRS and q does not, then there exist representations x and
y = applyTrans t x such that x ∼_P y but x ≁_Q y, so ∼_P ≠ ∼_Q.

For the nine derived profiles, every matrix difference that appears in a proof
involves a PRS cell for at least one of the two profiles being compared, so
the Lean definition is operationally equivalent to the paper's ∼_P ≠ ∼_Q.

Non-collapse is established in two stages:

  THM pairs (split pairs sharing a parent regime):
    ENR-L vs ENR-I: BF differs (PRS vs BRK). Proof: paper Prop. ENR non-collapse.
    CTX-E vs CTX-S: AD differs (PRS vs BRK). Proof: paper Prop. CTX non-collapse.
    NOR-C vs NOR-S: RF differs (PRS vs BRK). Proof: paper Prop. NOR non-collapse.

  GEN-CAR pairs (distinct parent regimes):
    Separated by difference in classification behavior across families.
    All 66 cross-family ordered pairs are handled by noncollapse_all_pairs.

Source: SE-300, Section 5, pairwise non-collapse matrices.
-/

namespace IdentityRegimes

/-- Two profiles are non-collapsing if the canonical classification matrix
    assigns different values to some transformation under those two profiles.

    This is sufficient for the paper's condition ∼_P ≠ ∼_Q: distinct PRS sets
    induce distinct equivalence relations on the representation space.
    See noncollapse_of_prs_difference for the operative connection. -/
def NonCollapsing (p q : RegimeProfileKind) : Prop :=
  ∃ t : Transformation, classificationMatrix p t ≠ classificationMatrix q t

-- ============================================================
-- CONNECTION TO ∼_P ≠ ∼_Q
-- ============================================================

/-- Core sufficiency lemma connecting the Lean definition to the paper.

    If profile p classifies transformation t as PRS and profile q does not,
    then p and q are non-collapsing: in the representation space R, any
    pair (x, applyTrans t x) is identity-related under p but not under q,
    so ∼_P ≠ ∼_Q.

    This theorem is the operative step in each paper non-collapse proof.
    All three split-pair proofs (ENR, CTX, NOR) instantiate this pattern:
      - noncollapse_ENR_L_ENR_I: t = BF, p = ENR-L (PRS), q = ENR-I (BRK)
      - noncollapse_CTX_E_CTX_S: t = AD, p = CTX-E (PRS), q = CTX-S (BRK)
      - noncollapse_NOR_C_NOR_S: t = RF, p = NOR-C (PRS), q = NOR-S (BRK) -/
theorem noncollapse_of_prs_difference
    (p q : RegimeProfileKind)
    (t : Transformation)
    (hp : classificationMatrix p t = .PRS)
    (hq : classificationMatrix q t ≠ .PRS) :
    NonCollapsing p q :=
    ⟨t, by
      rw [hp]
      intro h
      exact hq h.symm
    ⟩

-- ============================================================
-- THM pairs: split-theorem witnesses from the paper
-- ============================================================

/-- ENR-L and ENR-I are non-collapsing.
    BF: PRS under ENR-L (locus persists through branching),
        BRK under ENR-I (branching produces distinct artifacts).
    Instantiates noncollapse_of_prs_difference with t = BF.
    Source: SE-300 Prop. ENR non-collapse. -/
theorem noncollapse_ENR_L_ENR_I : NonCollapsing .ENR_L .ENR_I :=
  noncollapse_of_prs_difference .ENR_L .ENR_I .BF (by decide) (by decide)

/-- CTX-E and CTX-S are non-collapsing.
    AD: PRS under CTX-E (applicability extension preserved under decomposition),
        BRK under CTX-S (decomposition alters structural organization).
    Instantiates noncollapse_of_prs_difference with t = AD.
    Source: SE-300 Prop. CTX non-collapse. -/
theorem noncollapse_CTX_E_CTX_S : NonCollapsing .CTX_E .CTX_S :=
  noncollapse_of_prs_difference .CTX_E .CTX_S .AD (by decide) (by decide)

/-- NOR-C and NOR-S are non-collapsing.
    RF: PRS under NOR-C (refinement preserves normative content),
        BRK under NOR-S (refinement alters structural organization).
    Instantiates noncollapse_of_prs_difference with t = RF.
    Source: SE-300 Prop. NOR non-collapse. -/
theorem noncollapse_NOR_C_NOR_S : NonCollapsing .NOR_C .NOR_S :=
  noncollapse_of_prs_difference .NOR_C .NOR_S .RF (by decide) (by decide)

-- ============================================================
-- GEN-CAR pairs: cross-family separation
-- ============================================================

/-- Profiles with distinct parent regimes are non-collapsing. -/
theorem noncollapse_of_distinct_regime
    (p q : RegimeProfileKind)
    (h : p.regime ≠ q.regime) :
    NonCollapsing p q := by
  cases p <;> cases q <;>
    simp_all [RegimeProfileKind.regime] <;>
    first
    | exact ⟨.BF, by decide⟩
    | exact ⟨.AD, by decide⟩
    | exact ⟨.RF, by decide⟩
    | exact ⟨.SE, by decide⟩
    | exact ⟨.AN, by decide⟩
    | exact ⟨.RC, by decide⟩

/-- All 72 ordered pairs of distinct profiles in the derived regime set
    are non-collapsing under the canonical classification matrix. -/
theorem noncollapse_all_pairs
    (p q : RegimeProfileKind)
    (h : p ≠ q) :
    NonCollapsing p q := by
  cases p <;> cases q <;> simp_all <;>
    first
    | exact ⟨.BF, by native_decide⟩
    | exact ⟨.AD, by native_decide⟩
    | exact ⟨.RF, by native_decide⟩
    | exact ⟨.SE, by native_decide⟩
    | exact ⟨.AN, by native_decide⟩
    | exact ⟨.RC, by native_decide⟩
    | exact ⟨.RA, by native_decide⟩
    | exact ⟨.PV, by native_decide⟩
    | exact ⟨.SU, by native_decide⟩

end IdentityRegimes
